### ISSUE TITLE
Other hacktoberfest starter repository

### ISSUE THREAD

**Issue by ezralazuardy** [Dhroov7/Hacktoberfest2019#517]
https://github.com/ezralazuardy/hacktoberfest

**Comment by Iqlaas** [comment]
This repository has been archived by the owner. It is now read-only.

**Comment by ezralazuardy** [comment]
it's now opened :)

**Comment by Iqlaas** [comment]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the the core values of Hacktoberfest, so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of Hacktoberfest issues for inspiration and ideas about making meaningful contributions to open source projects.

Due to this, we've added this repository to our list of excluded repositories and pull requests here will not count toward Hacktoberfest 2019.

Please note, you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest.

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by DigitalOcean and DEV.

sorry to hear this. I just realised you are the owner. Nice intention.

**Comment by ezralazuardy** [comment]
;)
